-- ============================================================================
-- phase-26b — Platform Rights & Risk knowledge (Music Copyright + TikTok Risk)
--
-- Turns two reviewed research packs into review-gated candidate knowledge:
--   docs/ai-workforce/MUSIC-COPYRIGHT-PLATFORM-RIGHTS-SYSTEM.md  (MCR-01..10)
--   docs/ai-workforce/TIKTOK-HOSPITALITY-ENTERTAINMENT-RISK-PLAYBOOK.md (TIK-HOSP-01..08)
--
-- ALL cards are needs_review (never auto-active). Each carries a safe_claim, a
-- prohibited_overclaim (also inline in summary so retrieval conveys the boundary
-- with NO edge-function change), jurisdiction and a freshness review date. The CG
-- packs are stored as internal source records; official platform pages are cited.
-- Idempotent (sources by canonical_url, cards by slug). Additive.
-- ============================================================================

-- ── Sources ──────────────────────────────────────────────────────────────────
insert into public.marketing_library_sources
  (source_type, source_name, author_or_organisation, title, canonical_url,
   rights_status, rights_basis, access_mode, trust_tier, ingestion_status,
   rights_checked_at, rights_review_notes)
select * from (values
  ('official_documentation', 'TikTok Community Guidelines', 'TikTok',
   'TikTok Community Guidelines', 'https://www.tiktok.com/community-guidelines',
   'official_reference', 'Official TikTok policy; copyrighted.', 'metadata_and_link_only',
   'tier_1_primary', 'catalogued', now(), 'Enforcement framework, regulated goods, FYF eligibility. Cite + link only.'),
  ('official_documentation', 'TikTok Commercial Music Library', 'TikTok',
   'TikTok Commercial Music Library guidance', 'https://ads.tiktok.com/help/article/commercial-music-library',
   'official_reference', 'Official TikTok music guidance.', 'metadata_and_link_only',
   'tier_1_primary', 'catalogued', now(), 'CML pre-cleared for commercial use. Cite + link only.'),
  ('official_documentation', 'TikTok commercial use of music', 'TikTok',
   'Commercial use of music on TikTok', 'https://support.tiktok.com/en/business-and-creator/creator-and-business-accounts/commercial-use-of-music-on-tiktok',
   'official_reference', 'Official TikTok music guidance.', 'metadata_and_link_only',
   'tier_1_primary', 'catalogued', now(), 'Non-CML music not covered for brand content by default. Cite + link only.'),
  ('official_documentation', 'TikTok Promote advertising policies', 'TikTok',
   'TikTok advertising policies for Promote', 'https://ads.tiktok.com/help/article/about-tiktok-advertising-policies-for-promote',
   'official_reference', 'Official TikTok advertising guidance.', 'metadata_and_link_only',
   'tier_1_primary', 'catalogued', now(), 'Promote needs commercial-cleared sound; organic eligibility not automatic.'),
  ('official_documentation', 'Envato Elements Help', 'Envato',
   'Envato Elements licensing help', 'https://help.elements.envato.com/hc/en-us',
   'official_reference', 'Official Envato licensing documentation.', 'metadata_and_link_only',
   'tier_2_trusted_professional', 'catalogued', now(), 'Item licence + project registration + Claim Clear. Cite + link only.'),
  ('professional_source', 'CG Music Copyright & Platform Rights System', 'CG Production House (internal research)',
   'Music Copyright and Platform Rights System', 'docs/ai-workforce/MUSIC-COPYRIGHT-PLATFORM-RIGHTS-SYSTEM.md',
   'user_owned', 'CG-authored research synthesis of official platform sources.', 'internal_notes_only',
   'tier_3_internal_learning', 'catalogued', now(), 'CG internal synthesis; cites Meta/TikTok/YouTube/LinkedIn/Envato official pages.'),
  ('professional_source', 'CG TikTok Hospitality & Entertainment Risk Playbook', 'CG Production House (internal research)',
   'TikTok Hospitality and Entertainment Risk Playbook', 'docs/ai-workforce/TIKTOK-HOSPITALITY-ENTERTAINMENT-RISK-PLAYBOOK.md',
   'user_owned', 'CG-authored research synthesis of official TikTok policy.', 'internal_notes_only',
   'tier_3_internal_learning', 'catalogued', now(), 'CG internal synthesis; cites TikTok Community Guidelines, CML, Promote and ad-format pages.')
) as v(source_type, source_name, author_or_organisation, title, canonical_url,
   rights_status, rights_basis, access_mode, trust_tier, ingestion_status,
   rights_checked_at, rights_review_notes)
where not exists (select 1 from public.marketing_library_sources s where s.canonical_url = v.canonical_url);

-- ── Music & Copyright Rights cards (MCR-01..10) ──────────────────────────────
insert into public.skill_cards
  (slug, title, category, subcategory, status, knowledge_layer, source_id, source_type,
   confidence_level, evidence_label, principle, summary, why_it_matters,
   how_to_apply, mistakes_to_avoid, agent_instructions, relevant_industries, relevant_agents,
   client_specific, reference_state, jurisdiction, safe_claim, prohibited_overclaim, review_expires_at, notes, owner)
select v.slug, v.title, 'Music & Copyright Rights', v.subcategory, 'needs_review', 'universal_principle',
   src.id, 'official_documentation', v.confidence, 'platform_rule', v.principle, v.summary, v.why_it_matters,
   v.how_to_apply::jsonb, v.mistakes::jsonb, v.agent_instructions::jsonb, '[]'::jsonb,
   '["brand_guardian","social_media_strategist","content_planner","paid_ads_agent","creative_director","copywriting_agent"]'::jsonb,
   false, 'candidate_unverified', 'ZA; platform terms international', v.safe_claim, v.prohibited_overclaim, date '2026-10-31',
   'Seeded phase-26b from Music Copyright & Platform Rights System pack. Needs human review before active use.', 'ai-workforce-rights'
from (values
  ('mcr-01-availability-not-clearance', 'In-platform availability is not universal commercial clearance', 'Availability', 'high',
   'A song visible in a platform music library is not automatically cleared for every commercial use.',
   'Safe to say: in-platform availability depends on account type, post format, territory and commercial purpose. Never claim a song is "copyright-free" or cleared for a client business just because it appears in a platform library.',
   'Wrongly assuming in-app availability equals commercial clearance leads to muted/claimed client videos.',
   '["Confirm account type, post format, territory and commercial purpose before use","Prefer commercial-safe sources for client business content"]',
   '["Treating in-app availability as commercial clearance","Using the label copyright-free"]',
   '["Ask for platform, account type, organic/paid, format, territory and song source before answering","Cite the platform and reviewed date"]',
   'In-platform availability of a track depends on account type, post format, territory and commercial purpose.',
   'Never claim a song is copyright-free or cleared for a client business merely because it is available in the app.'),
  ('mcr-02-rights-not-portable', 'Music rights do not automatically travel between platforms', 'Portability', 'high',
   'A platform-specific music licence is not portable to other platforms unless its terms expressly allow it.',
   'Safe to say: a licence cleared on one platform is not automatically valid on another. Never claim a Meta/TikTok/YouTube library track is usable elsewhere without separate rights.',
   'Exporting platform-licensed music to another platform is a common cause of claims and takedowns.',
   '["Re-verify rights for each destination platform","Do not export platform-library music to another platform"]',
   '["Assuming a licence is portable across platforms"]',
   '["Treat each platform as a separate rights question"]',
   'A platform-specific licence applies only to that platform unless the terms say otherwise.',
   'Never claim music cleared on one platform is automatically cleared on another.'),
  ('mcr-03-royalty-free-still-copyright', 'Royalty-free still carries copyright and licence conditions', 'Licensing', 'high',
   'Royalty-free normally means no recurring royalties within scope, not the absence of copyright or conditions.',
   'Safe to say: royalty-free music still has a copyright owner and licence conditions; store the exact licence and project registration. Never treat royalty-free as no-copyright or condition-free.',
   'Misreading royalty-free as no-copyright leads to missing certificates and failed disputes.',
   '["Store the exact licence certificate and project registration","Record allowed platforms, formats and paid-use scope"]',
   '["Equating royalty-free with no copyright"]',
   '["Ask for the licence certificate and registered project before approving"]',
   'Royalty-free means no recurring royalties within the licence scope, not the absence of copyright.',
   'Never say royalty-free means there is no copyright or no conditions.'),
  ('mcr-04-meta-business-commercial-safe', 'Meta business content should prefer commercial-safe sources', 'Meta', 'high',
   'For client business content on Meta, prefer Sound Collection or a documented external commercial licence, not the personal licensed music library.',
   'Safe to say: for Meta client business content prefer Sound Collection or documented external rights, and treat boosting as paid/commercial use. Never assume the personal/creator licensed library covers a client business or that boosting keeps organic music rights.',
   'Instagram licensed music is intended for personal, non-commercial use; business accounts and post types can be restricted.',
   '["Prefer Meta Sound Collection or documented external rights for business content","Re-verify the licence when boosting"]',
   '["Assuming the personal licensed library covers a client business","Assuming boosting keeps organic music rights"]',
   '["Flag boosting as paid/commercial use requiring re-verification"]',
   'Meta client business content should use Sound Collection or documented external commercial rights; boosting is commercial use.',
   'Never assume the personal/creator licensed music library is cleared for a client business or that boosting preserves organic music rights.'),
  ('mcr-05-tiktok-brand-prefer-cml', 'TikTok brand content should prefer the Commercial Music Library', 'TikTok', 'high',
   'TikTok recommends the Commercial Music Library for content promoting a brand, product or service; non-CML music is not covered by default.',
   'Safe to say: for brand-promoting TikTok content use the Commercial Music Library, which is pre-cleared; non-CML music needs independent rights confirmation and the required disclosure. Never assume a general-library sound is cleared for a business post.',
   'Business accounts are directed to Commercial Sounds; the general library is for personal entertainment use.',
   '["Use the CML for brand content and record the sound ID","Confirm external rights and enable disclosure for non-CML music"]',
   '["Using general-library music on a brand post","Assuming organic-cleared sound is cleared for Promote/Ads"]',
   '["Confirm account type and organic/Promote/Ads before approving a sound"]',
   'Brand-promoting TikTok content should use the Commercial Music Library; non-CML music needs independent rights + disclosure.',
   'Never assume a general-library sound is cleared for a business/brand post or for Promote/Ads.'),
  ('mcr-06-youtube-claim-not-strike', 'A YouTube Content ID claim is not automatically a strike', 'YouTube', 'high',
   'A Content ID claim differs from a copyright strike/takedown; rights-holder policies (monetise, block, mute) can also change after publication.',
   'Safe to say: diagnose Content ID claim, block, mute and takedown as separate events; a claim is not automatically a strike. Never treat a Content ID claim as proof of infringement or as a strike.',
   'Conflating claim, block, mute and takedown produces wrong remedies and unnecessary strike risk.',
   '["Distinguish claim, block, mute and takedown","Keep the licence certificate to support disputes"]',
   '["Treating a Content ID claim as a strike or as proof of infringement"]',
   '["Ask for the exact notice wording before diagnosing a YouTube issue"]',
   'A Content ID claim is a separate event from a strike/takedown; policies can change after publication.',
   'Never say a Content ID claim is automatically a strike or proof the licence is invalid.'),
  ('mcr-07-envato-certificate-evidence', 'Envato certificate is operational evidence, register the exact project', 'Envato', 'high',
   'Envato items used in a larger end product require project registration and a stored licence certificate; the certificate supports claim resolution.',
   'Safe to say: register the exact client project in Envato and store the certificate before publishing; the video must be a larger end product, not a music-distribution substitute. Never assume one project registration covers unrelated client videos or that a certificate prevents automated claims.',
   'Missing project registration or certificate weakens disputes and can breach the licence scope.',
   '["Register the exact project and store the certificate before editing","Use Claim Clear where eligible"]',
   '["Reusing one project registration for unrelated client work","Assuming a certificate stops automated claims"]',
   '["Ask whether the exact project is registered and the certificate stored"]',
   'Register the exact Envato project and retain the certificate; it is evidence for claim resolution.',
   'Never assume one project registration covers unrelated videos or that a certificate prevents automated claims.'),
  ('mcr-08-licence-coexists-with-claims', 'A valid music licence can coexist with automated claims', 'Disputes', 'high',
   'A valid licence may still trigger an automated claim requiring clearance; a claim does not prove the licence is invalid.',
   'Safe to say: a valid licence can still generate an automated claim that needs clearing via the provider process; keep the certificate ready. Never treat an automated claim as proof the licence is invalid.',
   'Panic escalation of a valid-but-claimed track can create unnecessary strike risk.',
   '["Use the provider claim-clear/dispute process with the certificate","Do not casually escalate to a legal appeal"]',
   '["Assuming an automated claim means the licence is invalid"]',
   '["Route high-risk disputes to qualified review"]',
   'A valid licence and an automated claim can coexist; clear the claim via the provider process.',
   'Never say an automated claim proves the licence is invalid.'),
  ('mcr-09-ambient-event-music-risk', 'Ambient event music can create copyright risk', 'Capture', 'high',
   'Recording music at a venue or event does not by itself grant the right to publish it.',
   'Safe to say: incidentally captured background music at an event still carries copyright risk. Never treat ambient music captured on location as automatically cleared for publication.',
   'Ambient copyrighted music is a frequent hidden cause of mutes and claims on event content.',
   '["Assess ambient copyrighted music before publishing","Prefer a clean master with original/licensed audio"]',
   '["Treating incidentally captured music as cleared"]',
   '["Flag ambient event music as a rights risk to check"]',
   'Ambient music captured on location still carries copyright risk.',
   'Never treat incidentally recorded event music as automatically cleared for publication.'),
  ('mcr-10-rights-can-change', 'Music rights can change after publication', 'Freshness', 'high',
   'Platform or rights-holder agreements can later cause muting, blocking or changed monetisation of already-published content.',
   'Safe to say: platform-licensed music may later be muted or claimed because rights can change after publication; keep proof and an incident owner. Never guarantee that a currently-cleared track will stay cleared permanently.',
   'Assuming a one-time clearance is permanent leaves clients exposed to later mutes/claims.',
   '["Keep the licence proof and assign an incident owner","Re-verify rights on long-running or reused content"]',
   '["Guaranteeing permanent clearance"]',
   '["State that rights can change and cite the reviewed date"]',
   'Platform/rights-holder changes can alter a published video''s music status later.',
   'Never guarantee that a currently-cleared track will remain cleared permanently.')
) as v(slug, title, subcategory, confidence, principle, summary, why_it_matters, how_to_apply, mistakes, agent_instructions, safe_claim, prohibited_overclaim)
join public.marketing_library_sources src on src.canonical_url = 'docs/ai-workforce/MUSIC-COPYRIGHT-PLATFORM-RIGHTS-SYSTEM.md'
where not exists (select 1 from public.skill_cards sc where sc.slug = v.slug);

-- ── TikTok Platform Risk cards (TIK-HOSP-01..08) ─────────────────────────────
insert into public.skill_cards
  (slug, title, category, subcategory, status, knowledge_layer, source_id, source_type,
   confidence_level, evidence_label, principle, summary, why_it_matters,
   how_to_apply, mistakes_to_avoid, agent_instructions, relevant_industries, relevant_agents,
   client_specific, reference_state, jurisdiction, safe_claim, prohibited_overclaim, review_expires_at, notes, owner)
select v.slug, v.title, 'TikTok Platform Risk', v.subcategory, 'needs_review', 'universal_principle',
   src.id, 'official_documentation', v.confidence, 'platform_rule', v.principle, v.summary, v.why_it_matters,
   v.how_to_apply::jsonb, v.mistakes::jsonb, v.agent_instructions::jsonb, '["hospitality","entertainment"]'::jsonb,
   '["brand_guardian","social_media_strategist","content_planner","paid_ads_agent","creative_director"]'::jsonb,
   false, 'candidate_unverified', 'ZA; TikTok global policy', v.safe_claim, v.prohibited_overclaim, date '2026-10-31',
   'Seeded phase-26b from TikTok Hospitality & Entertainment Risk Playbook. Needs human review before active use.', 'ai-workforce-rights'
from (values
  ('tik-hosp-01-preserve-enforcement-state', 'Preserve the exact TikTok enforcement state', 'Enforcement', 'high',
   'Removal, For-You-feed ineligibility, age restriction, sound muting and account action are different events with different remedies.',
   'Safe to say: distinguish removal, FYF-ineligibility, age-restriction, sound-muting and account action; each needs a different remedy. Never collapse them into one "violation" or claim the cause without the exact TikTok notice.',
   'Wrong remedy and wrong client advice follow from collapsing distinct enforcement actions.',
   '["Record the exact notice wording and enforcement type","Map each incident to one policy category"]',
   '["Storing only community guidelines violation as the reason","Guessing the cause without the notice"]',
   '["Ask for the exact TikTok notice, post, sound, account type and appeal history before diagnosing"]',
   'TikTok enforcement actions are distinct events requiring distinct remedies.',
   'Never collapse different TikTok actions into one violation or claim a cause without the exact notice.'),
  ('tik-hosp-02-venue-content-commercial', 'Venue content is commercial even when informal', 'Disclosure', 'high',
   'Informal, staff-led venue content can still promote the business and should follow commercial disclosure and music rules.',
   'Safe to say: a venue account is commercial content even when a post feels casual; use the commercial-content disclosure and commercial-cleared music. Never assume informal or staff-led content is exempt from commercial disclosure and music rules.',
   'Missing disclosure or general-library music on commercial posts drives enforcement.',
   '["Use the required commercial-content disclosure","Use commercial-cleared music for venue posts"]',
   '["Treating staff-led content as non-commercial"]',
   '["Confirm the account type and whether the post promotes the venue/offer"]',
   'Venue/brand content is commercial even when informal; disclosure and commercial music rules apply.',
   'Never assume informal or staff-led venue content is exempt from commercial disclosure or music rules.'),
  ('tik-hosp-03-alcohol-trade-broader', 'Alcohol trade risk is broader than showing a drink', 'Regulated goods', 'high',
   'Captions, CTAs, contact details, giveaways and off-platform redirection can create regulated-goods risk even when no drink appears.',
   'Safe to say: alcohol-trade risk comes from captions, CTAs, contact details, giveaways and redirection, not only a visible drink; showing an adult venue/bottle is not automatically prohibited trade. Never claim a specific post broke alcohol rules without the full post package and notice.',
   'Both over- and under-calling alcohol risk harm clients; context and CTA matter, not just visible alcohol.',
   '["Check caption, CTA, contact details, giveaways and redirection for trade signals","Keep venue identity broader than alcohol-only"]',
   '["Assuming a visible drink equals prohibited trade","Ignoring caption/CTA trade signals"]',
   '["Assess the whole video, caption, overlays, sound, hashtags, account identity and CTA"]',
   'Alcohol-trade risk arises from CTA/caption/contact/giveaway/redirection context, not only a visible drink.',
   'Never claim a post broke alcohol-trade rules without the full post package and the exact notice.'),
  ('tik-hosp-04-excessive-drinking-recommendation-risk', 'Excessive drinking is a recommendation risk; minors must not be shown with alcohol', 'Regulated goods', 'high',
   'Adult excessive alcohol consumption can be age-restricted and excluded from the For You feed; minors may not be shown possessing or using alcohol.',
   'Safe to say: excessive-drinking and intoxication content can be age-restricted and made FYF-ineligible, and minors must never be shown with alcohol. Never recommend drinking challenges, speed-drinking or intoxication content.',
   'Drinking-challenge and intoxication content is high enforcement and safety risk.',
   '["Avoid excessive-drinking, challenge and intoxication content","Ensure no minor or age-ambiguous person is shown with alcohol"]',
   '["Recommending drinking games or speed-drinking","Showing young-looking people with alcohol"]',
   '["Refuse to plan drinking-challenge or minor-with-alcohol content"]',
   'Excessive adult drinking can be age-restricted/FYF-ineligible; minors must never appear with alcohol.',
   'Never recommend drinking challenges, speed-drinking, intoxication content, or minors with alcohol.'),
  ('tik-hosp-05-tiktok-music-account-use-specific', 'TikTok music clearance is account- and use-specific', 'Music', 'high',
   'A sound in TikTok''s general library is not automatically licensed for a business''s commercial post.',
   'Safe to say: for commercial TikTok posts use the Commercial Music Library and confirm region, placement and usable duration; the general library is not automatically licensed for business use. Never assume a general-library sound is cleared for a brand/business post.',
   'General-library music on commercial posts is a leading mute/removal cause.',
   '["Use the CML and confirm region, placement and usable duration","Keep a clean master with original/licensed audio"]',
   '["Using general-library music on a business post"]',
   '["Confirm account type and organic/Promote/Ads before approving a sound"]',
   'TikTok music clearance depends on account type and use; the general library is not auto-licensed for business.',
   'Never assume a general-library sound is cleared for a brand or business post.'),
  ('tik-hosp-06-one-minute-not-universal-mute', 'One minute is not a universal organic mute rule', 'Music', 'high',
   'There is no verified universal rule that every organic TikTok over 60 seconds is muted; causes vary.',
   'Safe to say: check sound usable duration, music rights, account type, region/placement and whether the flow is organic, Promote or Ads before attributing a mute to length; the 5–60s spec is an ad-format rule. Never claim all organic videos over one minute are muted.',
   'The 60-second myth misdiagnoses mutes and hides the real cause.',
   '["Check sound duration, rights, account type, placement and organic/Promote/Ads","Treat 5-60s as an ad-format rule only"]',
   '["Claiming all organic posts over 60s are muted","Converting the ad-format rule into an organic rule"]',
   '["Diagnose the exact mute cause from the notice and sound source"]',
   'A mute can have several causes; the 5-60s duration is an ad-format spec, not an organic rule.',
   'Never claim every organic TikTok over one minute is muted.'),
  ('tik-hosp-07-original-footage-reduces-risk', 'Original venue footage reduces several risks', 'Originality', 'medium',
   'Original footage without third-party watermarks, embedded copyrighted music or broadcast material is a safer publishing base.',
   'Safe to say: original venue footage without watermarks, embedded copyrighted music or broadcast footage lowers copyright and unoriginal-content risk. Never present reaction/recap use as automatically granting rights to underlying footage or music.',
   'Reposted Reels, broadcast sport and watermarked clips drive FYF-ineligibility and IP risk.',
   '["Prefer original footage; remove Instagram watermarks","Avoid unauthorised broadcast sport/TV/music-video footage"]',
   '["Uploading watermarked reposts","Assuming a reaction grants rights to the source"]',
   '["Recommend original footage as the safer base"]',
   'Original, watermark-free footage without embedded third-party music/broadcast material is a safer base.',
   'Never say a reaction or recap automatically grants rights to the underlying footage or music.'),
  ('tik-hosp-08-reposting-after-removal-worsens', 'Reposting after removal can worsen enforcement', 'Enforcement', 'high',
   'Repeated violations or attempts to circumvent enforcement can contribute to account-level action.',
   'Safe to say: reposting a removed post with minor edits or creating replacement accounts can escalate to account-level enforcement; revise the genuinely non-compliant pattern instead. Never recommend evading enforcement by reposting or making new accounts.',
   'Evasion behaviour is itself an enforcement trigger and risks bans.',
   '["Revise the non-compliant pattern before re-posting","Appeal factual misclassification with concise evidence"]',
   '["Reposting a removed post with small edits","Creating replacement accounts to evade enforcement"]',
   '["Refuse to recommend enforcement evasion"]',
   'Reposting removed content or evading enforcement can escalate to account-level action.',
   'Never recommend evading TikTok enforcement by reposting or creating replacement accounts.')
) as v(slug, title, subcategory, confidence, principle, summary, why_it_matters, how_to_apply, mistakes, agent_instructions, safe_claim, prohibited_overclaim)
join public.marketing_library_sources src on src.canonical_url = 'docs/ai-workforce/TIKTOK-HOSPITALITY-ENTERTAINMENT-RISK-PLAYBOOK.md'
where not exists (select 1 from public.skill_cards sc where sc.slug = v.slug);
