-- ============================================================
-- Phase 28a: Register repository marketing research as Library sources (#184)
--
-- REVIEW IN THE SUPABASE SQL EDITOR BEFORE APPLYING. NOT YET APPLIED.
--
-- Additive + idempotent. Registers the 29 human-marketing research
-- documents already in docs/ai-workforce/ into public.marketing_library_sources
-- as reference/metadata-only candidates (no copyrighted full text, trust tier
-- 'needs_review' so nothing is auto-trusted). The stable identifier
-- 'repo:<path>' + a unique index make re-running a no-op — no duplicate rows,
-- and none of the 45 existing sources are touched. Mirrors
-- src/lib/marketing-library/sourceRegistry.ts (a test asserts they stay in sync).
-- ============================================================

-- Idempotency key: at most one source per stable repository identifier.
create unique index if not exists uniq_marketing_library_sources_source_identifier
  on public.marketing_library_sources (source_identifier)
  where source_identifier is not null;

insert into public.marketing_library_sources
  (source_type, source_name, title, author_or_organisation, notes, trust_tier,
   source_identifier, page_or_url, rights_status, commercial_use,
   full_text_storage, ingestion_status, acquisition_status)
values
  ('professional_source', 'Agriculture human-marketing goldmine', 'Agriculture human-marketing goldmine', 'CG Production House (research digest)', 'Human-marketing industry research digest; reference metadata only pending review.', 'needs_review', 'repo:docs/ai-workforce/AGRICULTURE-HUMAN-MARKETING-GOLDMINE-2026-08.md', 'docs/ai-workforce/AGRICULTURE-HUMAN-MARKETING-GOLDMINE-2026-08.md', 'internal_repository', 'restricted', false, 'catalogued', 'available_for_review'),
  ('professional_source', 'Automotive human-marketing goldmine', 'Automotive human-marketing goldmine', 'CG Production House (research digest)', 'Human-marketing industry research digest; reference metadata only pending review.', 'needs_review', 'repo:docs/ai-workforce/AUTOMOTIVE-HUMAN-MARKETING-GOLDMINE-2026-08.md', 'docs/ai-workforce/AUTOMOTIVE-HUMAN-MARKETING-GOLDMINE-2026-08.md', 'internal_repository', 'restricted', false, 'catalogued', 'available_for_review'),
  ('professional_source', 'B2B manufacturing & industrial suppliers goldmine', 'B2B manufacturing & industrial suppliers goldmine', 'CG Production House (research digest)', 'Human-marketing industry research digest; reference metadata only pending review.', 'needs_review', 'repo:docs/ai-workforce/B2B-MANUFACTURING-INDUSTRIAL-SUPPLIERS-HUMAN-MARKETING-GOLDMINE-2026-08.md', 'docs/ai-workforce/B2B-MANUFACTURING-INDUSTRIAL-SUPPLIERS-HUMAN-MARKETING-GOLDMINE-2026-08.md', 'internal_repository', 'restricted', false, 'catalogued', 'available_for_review'),
  ('professional_source', 'Building materials & home improvement goldmine', 'Building materials & home improvement goldmine', 'CG Production House (research digest)', 'Human-marketing industry research digest; reference metadata only pending review.', 'needs_review', 'repo:docs/ai-workforce/BUILDING-MATERIALS-HUMAN-MARKETING-GOLDMINE-2026-08.md', 'docs/ai-workforce/BUILDING-MATERIALS-HUMAN-MARKETING-GOLDMINE-2026-08.md', 'internal_repository', 'restricted', false, 'catalogued', 'available_for_review'),
  ('professional_source', 'Building sustainability & green energy goldmine', 'Building sustainability & green energy goldmine', 'CG Production House (research digest)', 'Human-marketing industry research digest; reference metadata only pending review.', 'needs_review', 'repo:docs/ai-workforce/BUILDING-MATERIALS-SUSTAINABILITY-GREEN-ENERGY-MARKETING-GOLDMINE-2026-08.md', 'docs/ai-workforce/BUILDING-MATERIALS-SUSTAINABILITY-GREEN-ENERGY-MARKETING-GOLDMINE-2026-08.md', 'internal_repository', 'restricted', false, 'catalogued', 'available_for_review'),
  ('professional_source', 'Community, sport & entertainment goldmine', 'Community, sport & entertainment goldmine', 'CG Production House (research digest)', 'Human-marketing industry research digest; reference metadata only pending review.', 'needs_review', 'repo:docs/ai-workforce/COMMUNITY-SPORT-ENTERTAINMENT-HUMAN-MARKETING-GOLDMINE-2026-08.md', 'docs/ai-workforce/COMMUNITY-SPORT-ENTERTAINMENT-HUMAN-MARKETING-GOLDMINE-2026-08.md', 'internal_repository', 'restricted', false, 'catalogued', 'available_for_review'),
  ('professional_source', 'Education, training & skills development goldmine', 'Education, training & skills development goldmine', 'CG Production House (research digest)', 'Human-marketing industry research digest; reference metadata only pending review.', 'needs_review', 'repo:docs/ai-workforce/EDUCATION-TRAINING-SKILLS-DEVELOPMENT-HUMAN-MARKETING-GOLDMINE-2026-08.md', 'docs/ai-workforce/EDUCATION-TRAINING-SKILLS-DEVELOPMENT-HUMAN-MARKETING-GOLDMINE-2026-08.md', 'internal_repository', 'restricted', false, 'catalogued', 'available_for_review'),
  ('professional_source', 'Financial, insurance & credit services goldmine', 'Financial, insurance & credit services goldmine', 'CG Production House (research digest)', 'Human-marketing industry research digest; reference metadata only pending review.', 'needs_review', 'repo:docs/ai-workforce/FINANCIAL-INSURANCE-CREDIT-SERVICES-HUMAN-MARKETING-GOLDMINE-2026-08.md', 'docs/ai-workforce/FINANCIAL-INSURANCE-CREDIT-SERVICES-HUMAN-MARKETING-GOLDMINE-2026-08.md', 'internal_repository', 'restricted', false, 'catalogued', 'available_for_review'),
  ('professional_source', 'Healthcare, wellness & medical services goldmine', 'Healthcare, wellness & medical services goldmine', 'CG Production House (research digest)', 'Human-marketing industry research digest; reference metadata only pending review.', 'needs_review', 'repo:docs/ai-workforce/HEALTHCARE-WELLNESS-MEDICAL-SERVICES-HUMAN-MARKETING-GOLDMINE-2026-08.md', 'docs/ai-workforce/HEALTHCARE-WELLNESS-MEDICAL-SERVICES-HUMAN-MARKETING-GOLDMINE-2026-08.md', 'internal_repository', 'restricted', false, 'catalogued', 'available_for_review'),
  ('professional_source', 'Hospitality, restaurants, bars & events goldmine', 'Hospitality, restaurants, bars & events goldmine', 'CG Production House (research digest)', 'Human-marketing industry research digest; reference metadata only pending review.', 'needs_review', 'repo:docs/ai-workforce/HOSPITALITY-RESTAURANTS-BARS-EVENTS-HUMAN-MARKETING-GOLDMINE-2026-08.md', 'docs/ai-workforce/HOSPITALITY-RESTAURANTS-BARS-EVENTS-HUMAN-MARKETING-GOLDMINE-2026-08.md', 'internal_repository', 'restricted', false, 'catalogued', 'available_for_review'),
  ('professional_source', 'Legal & professional services goldmine', 'Legal & professional services goldmine', 'CG Production House (research digest)', 'Human-marketing industry research digest; reference metadata only pending review.', 'needs_review', 'repo:docs/ai-workforce/LEGAL-PROFESSIONAL-SERVICES-HUMAN-MARKETING-GOLDMINE-2026-08.md', 'docs/ai-workforce/LEGAL-PROFESSIONAL-SERVICES-HUMAN-MARKETING-GOLDMINE-2026-08.md', 'internal_repository', 'restricted', false, 'catalogued', 'available_for_review'),
  ('professional_source', 'Music, entertainment & creators goldmine', 'Music, entertainment & creators goldmine', 'CG Production House (research digest)', 'Human-marketing industry research digest; reference metadata only pending review.', 'needs_review', 'repo:docs/ai-workforce/MUSIC-ENTERTAINMENT-CREATORS-HUMAN-MARKETING-GOLDMINE-2026-08.md', 'docs/ai-workforce/MUSIC-ENTERTAINMENT-CREATORS-HUMAN-MARKETING-GOLDMINE-2026-08.md', 'internal_repository', 'restricted', false, 'catalogued', 'available_for_review'),
  ('professional_source', 'Property, architecture & construction services goldmine', 'Property, architecture & construction services goldmine', 'CG Production House (research digest)', 'Human-marketing industry research digest; reference metadata only pending review.', 'needs_review', 'repo:docs/ai-workforce/PROPERTY-ARCHITECTURE-CONSTRUCTION-SERVICES-HUMAN-MARKETING-GOLDMINE-2026-08.md', 'docs/ai-workforce/PROPERTY-ARCHITECTURE-CONSTRUCTION-SERVICES-HUMAN-MARKETING-GOLDMINE-2026-08.md', 'internal_repository', 'restricted', false, 'catalogued', 'available_for_review'),
  ('professional_source', 'Retail & ecommerce goldmine', 'Retail & ecommerce goldmine', 'CG Production House (research digest)', 'Human-marketing industry research digest; reference metadata only pending review.', 'needs_review', 'repo:docs/ai-workforce/RETAIL-ECOMMERCE-HUMAN-MARKETING-GOLDMINE-2026-08.md', 'docs/ai-workforce/RETAIL-ECOMMERCE-HUMAN-MARKETING-GOLDMINE-2026-08.md', 'internal_repository', 'restricted', false, 'catalogued', 'available_for_review'),
  ('professional_source', 'Security, guarding & risk services goldmine', 'Security, guarding & risk services goldmine', 'CG Production House (research digest)', 'Human-marketing industry research digest; reference metadata only pending review.', 'needs_review', 'repo:docs/ai-workforce/SECURITY-GUARDING-SURVEILLANCE-RISK-SERVICES-HUMAN-MARKETING-GOLDMINE-2026-08.md', 'docs/ai-workforce/SECURITY-GUARDING-SURVEILLANCE-RISK-SERVICES-HUMAN-MARKETING-GOLDMINE-2026-08.md', 'internal_repository', 'restricted', false, 'catalogued', 'available_for_review'),
  ('professional_source', 'Tourism, accommodation & destinations goldmine', 'Tourism, accommodation & destinations goldmine', 'CG Production House (research digest)', 'Human-marketing industry research digest; reference metadata only pending review.', 'needs_review', 'repo:docs/ai-workforce/TOURISM-ACCOMMODATION-DESTINATION-HUMAN-MARKETING-GOLDMINE-2026-08.md', 'docs/ai-workforce/TOURISM-ACCOMMODATION-DESTINATION-HUMAN-MARKETING-GOLDMINE-2026-08.md', 'internal_repository', 'restricted', false, 'catalogued', 'available_for_review'),
  ('professional_source', 'Brand strategy & creative effectiveness source pack', 'Brand strategy & creative effectiveness source pack', 'CG Production House (research digest)', 'Cross-industry marketing source pack; reference metadata only pending review.', 'needs_review', 'repo:docs/ai-workforce/BRAND-STRATEGY-CREATIVE-EFFECTIVENESS-SOURCE-PACK.md', 'docs/ai-workforce/BRAND-STRATEGY-CREATIVE-EFFECTIVENESS-SOURCE-PACK.md', 'internal_repository', 'restricted', false, 'catalogued', 'available_for_review'),
  ('professional_source', 'Conversion & experimentation source pack', 'Conversion & experimentation source pack', 'CG Production House (research digest)', 'Cross-industry marketing source pack; reference metadata only pending review.', 'needs_review', 'repo:docs/ai-workforce/CONVERSION-EXPERIMENTATION-SOURCE-PACK.md', 'docs/ai-workforce/CONVERSION-EXPERIMENTATION-SOURCE-PACK.md', 'internal_repository', 'restricted', false, 'catalogued', 'available_for_review'),
  ('professional_source', 'Creator & influencer partnership source pack', 'Creator & influencer partnership source pack', 'CG Production House (research digest)', 'Cross-industry marketing source pack; reference metadata only pending review.', 'needs_review', 'repo:docs/ai-workforce/CREATOR-INFLUENCER-PARTNERSHIP-SOURCE-PACK.md', 'docs/ai-workforce/CREATOR-INFLUENCER-PARTNERSHIP-SOURCE-PACK.md', 'internal_repository', 'restricted', false, 'catalogued', 'available_for_review'),
  ('professional_source', 'Hooks & trend-led creative source pack', 'Hooks & trend-led creative source pack', 'CG Production House (research digest)', 'Cross-industry marketing source pack; reference metadata only pending review.', 'needs_review', 'repo:docs/ai-workforce/HOOKS-TREND-LED-CREATIVE-SOURCE-PACK.md', 'docs/ai-workforce/HOOKS-TREND-LED-CREATIVE-SOURCE-PACK.md', 'internal_repository', 'restricted', false, 'catalogued', 'available_for_review'),
  ('professional_source', 'Landing page, offer & conversion writing source pack', 'Landing page, offer & conversion writing source pack', 'CG Production House (research digest)', 'Cross-industry marketing source pack; reference metadata only pending review.', 'needs_review', 'repo:docs/ai-workforce/LANDING-PAGE-OFFER-CONVERSION-WRITING-SOURCE-PACK.md', 'docs/ai-workforce/LANDING-PAGE-OFFER-CONVERSION-WRITING-SOURCE-PACK.md', 'internal_repository', 'restricted', false, 'catalogued', 'available_for_review'),
  ('professional_source', 'Lifecycle, messaging & CRM source pack', 'Lifecycle, messaging & CRM source pack', 'CG Production House (research digest)', 'Cross-industry marketing source pack; reference metadata only pending review.', 'needs_review', 'repo:docs/ai-workforce/LIFECYCLE-MESSAGING-CRM-SOURCE-PACK.md', 'docs/ai-workforce/LIFECYCLE-MESSAGING-CRM-SOURCE-PACK.md', 'internal_repository', 'restricted', false, 'catalogued', 'available_for_review'),
  ('professional_source', 'Local marketing & reputation source pack', 'Local marketing & reputation source pack', 'CG Production House (research digest)', 'Cross-industry marketing source pack; reference metadata only pending review.', 'needs_review', 'repo:docs/ai-workforce/LOCAL-MARKETING-REPUTATION-SOURCE-PACK.md', 'docs/ai-workforce/LOCAL-MARKETING-REPUTATION-SOURCE-PACK.md', 'internal_repository', 'restricted', false, 'catalogued', 'available_for_review'),
  ('professional_source', 'Paid ads, website & leads source pack', 'Paid ads, website & leads source pack', 'CG Production House (research digest)', 'Cross-industry marketing source pack; reference metadata only pending review.', 'needs_review', 'repo:docs/ai-workforce/PAID-ADS-WEBSITE-LEADS-SOURCE-PACK.md', 'docs/ai-workforce/PAID-ADS-WEBSITE-LEADS-SOURCE-PACK.md', 'internal_repository', 'restricted', false, 'catalogued', 'available_for_review'),
  ('professional_source', 'Shopify & commerce platform source pack', 'Shopify & commerce platform source pack', 'CG Production House (research digest)', 'Cross-industry marketing source pack; reference metadata only pending review.', 'needs_review', 'repo:docs/ai-workforce/SHOPIFY-COMMERCE-PLATFORM-SOURCE-PACK.md', 'docs/ai-workforce/SHOPIFY-COMMERCE-PLATFORM-SOURCE-PACK.md', 'internal_repository', 'restricted', false, 'catalogued', 'available_for_review'),
  ('professional_source', 'Social-native short-form storytelling source pack', 'Social-native short-form storytelling source pack', 'CG Production House (research digest)', 'Cross-industry marketing source pack; reference metadata only pending review.', 'needs_review', 'repo:docs/ai-workforce/SOCIAL-NATIVE-SHORT-FORM-STORYTELLING-SOURCE-PACK.md', 'docs/ai-workforce/SOCIAL-NATIVE-SHORT-FORM-STORYTELLING-SOURCE-PACK.md', 'internal_repository', 'restricted', false, 'catalogued', 'available_for_review'),
  ('professional_source', 'Storytelling & scriptwriting craft source pack', 'Storytelling & scriptwriting craft source pack', 'CG Production House (research digest)', 'Cross-industry marketing source pack; reference metadata only pending review.', 'needs_review', 'repo:docs/ai-workforce/STORYTELLING-SCRIPTWRITING-SHORT-FORM-CRAFT-SOURCE-PACK.md', 'docs/ai-workforce/STORYTELLING-SCRIPTWRITING-SHORT-FORM-CRAFT-SOURCE-PACK.md', 'internal_repository', 'restricted', false, 'catalogued', 'available_for_review'),
  ('professional_source', 'Strategy, research & historical advertising source pack', 'Strategy, research & historical advertising source pack', 'CG Production House (research digest)', 'Cross-industry marketing source pack; reference metadata only pending review.', 'needs_review', 'repo:docs/ai-workforce/STRATEGY-RESEARCH-HISTORICAL-SOURCE-PACK.md', 'docs/ai-workforce/STRATEGY-RESEARCH-HISTORICAL-SOURCE-PACK.md', 'internal_repository', 'restricted', false, 'catalogued', 'available_for_review'),
  ('professional_source', 'Video, photography & sound editing craft source pack', 'Video, photography & sound editing craft source pack', 'CG Production House (research digest)', 'Cross-industry marketing source pack; reference metadata only pending review.', 'needs_review', 'repo:docs/ai-workforce/VIDEO-PHOTOGRAPHY-SOUND-EDITING-CRAFT-SOURCE-PACK.md', 'docs/ai-workforce/VIDEO-PHOTOGRAPHY-SOUND-EDITING-CRAFT-SOURCE-PACK.md', 'internal_repository', 'restricted', false, 'catalogued', 'available_for_review')
on conflict (source_identifier) do nothing;

-- ── Verification (run manually after applying) ───────────────────────────────
-- select count(*) from public.marketing_library_sources
--   where source_identifier like 'repo:docs/ai-workforce/%';   -- expect 29
-- Re-running this file inserts zero additional rows.
-- ============================================================
