import type { SkillCard } from '../../../types/skillCards'

export const sampleSkillCards: SkillCard[] = [
  {
    id: 'industry-real-estate-trust-before-cta',
    title: 'Trust signal before enquiry CTA',
    category: 'Industry Libraries',
    subcategory: 'Real estate',
    status: 'needs_review',
    lastReviewed: null,
    knowledgeLayer: 'industry_specific',
    sourceType: 'staff_observation',
    sourceReference: {
      sourceType: 'staff_observation',
      sourceName: 'CG Production House internal observation',
      interpretationNotes: 'Working hypothesis for review. Not yet supported by a verified external source.',
    },
    confidenceLevel: 'opinion',
    evidenceLabel: 'hypothesis',
    relevantIndustries: ['real_estate'],
    relevantAgents: ['marketing_strategist', 'copywriting_agent', 'creative_director_agent'],
    principle: 'Real estate content should reduce buyer or seller uncertainty before asking for an enquiry.',
    summary: 'Property audiences often need proof, context or reassurance before taking the next step.',
    whyItMatters: 'A direct CTA can feel premature when the audience has not yet seen enough reason to trust the agent or listing.',
    howToApply: [
      'Show a clear trust cue before the CTA.',
      'Use specific property, area or process context instead of vague claims.',
      'Keep the CTA practical and low friction.',
    ],
    examples: [
      'Use area knowledge, sold examples or viewing process clarity before asking someone to book a viewing.',
    ],
    mistakesToAvoid: [
      'Do not claim market leadership without evidence.',
      'Do not rely on generic luxury wording without specific proof.',
    ],
    agentInstructions: [
      'Use this only as a draft hypothesis until reviewed.',
      'Do not present this as proven real estate research.',
    ],
    relatedCardIds: [],
    notes: 'Industry-only example. No client data used.',
    clientSpecific: false,
  },
  {
    id: 'industry-hospitality-menu-specificity',
    title: 'Specific dish cues beat vague appetite hooks',
    category: 'Industry Libraries',
    subcategory: 'Restaurants and hospitality',
    status: 'needs_review',
    lastReviewed: null,
    knowledgeLayer: 'industry_specific',
    sourceType: 'staff_observation',
    sourceReference: {
      sourceType: 'staff_observation',
      sourceName: 'CG Production House internal observation',
      interpretationNotes: 'Draft observation for future testing against campaign performance data.',
    },
    confidenceLevel: 'opinion',
    evidenceLabel: 'hypothesis',
    relevantIndustries: ['restaurants_hospitality'],
    relevantAgents: ['copywriting_agent', 'graphic_design_first_draft_agent', 'brand_guardian'],
    principle: 'Restaurant content should make the product concrete before using appetite language.',
    summary: 'Specific dish names, ingredients, formats or moments are usually more useful than vague food adjectives.',
    whyItMatters: 'Concrete details help the audience imagine the meal and decide whether it fits the occasion.',
    howToApply: [
      'Lead with the dish, occasion or offer.',
      'Use sensory wording only after the product is clear.',
      'Match the CTA to the buying path: book, order, visit or enquire.',
    ],
    examples: [
      'A lunch-special post should name the special before saying it is delicious.',
    ],
    mistakesToAvoid: [
      'Do not write only generic appetite hooks.',
      'Do not hide the actual dish or offer behind lifestyle wording.',
    ],
    agentInstructions: [
      'Flag captions that sound appetising but never name the item or offer.',
      'Keep this as needs review until supported by data or external research.',
    ],
    relatedCardIds: [],
    notes: 'Industry-only example. No client data used.',
    clientSpecific: false,
  },
  {
    id: 'industry-automotive-risk-reduction',
    title: 'Reduce risk before pushing urgency',
    category: 'Industry Libraries',
    subcategory: 'Automotive',
    status: 'needs_review',
    lastReviewed: null,
    knowledgeLayer: 'industry_specific',
    sourceType: 'staff_observation',
    sourceReference: {
      sourceType: 'staff_observation',
      sourceName: 'CG Production House internal observation',
      interpretationNotes: 'Draft hypothesis for later validation with automotive campaign results.',
    },
    confidenceLevel: 'opinion',
    evidenceLabel: 'hypothesis',
    relevantIndustries: ['automotive'],
    relevantAgents: ['marketing_strategist', 'paid_ads_agent', 'client_report_agent'],
    principle: 'Automotive offers should answer risk questions before relying on urgency.',
    summary: 'Vehicle and service buyers often need clarity on condition, warranty, finance, availability or process.',
    whyItMatters: 'Urgency can attract attention, but unanswered risk can stop the enquiry.',
    howToApply: [
      'State the practical risk reducer clearly.',
      'Keep urgency secondary unless it is factual.',
      'Avoid unsupported claims about best price or guaranteed approval.',
    ],
    examples: [
      'A vehicle ad should clarify finance, warranty or inspection details before pushing limited availability.',
    ],
    mistakesToAvoid: [
      'Do not create false scarcity.',
      'Do not make finance or warranty claims without verification.',
    ],
    agentInstructions: [
      'Use this card to review whether automotive copy answers the buyer risk question.',
      'Keep claims conservative unless client-approved proof exists.',
    ],
    relatedCardIds: [],
    notes: 'Industry-only example. No client data used.',
    clientSpecific: false,
  },
]
